[build]
  base = "/"
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.18.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
